language: go
sudo: required
go:
  - 1.11.1
services:
  - docker
install: true
script: make travis
deploy:
  skip_cleanup: true
  provider: releases
  api_key:
    secure: iUScy9FBiiU2e2NdCotlP/HozuF1WpeYKUQoxbUB1lfZe25HO4VpUbgEwWzTwxuYI19+iOEnt4LgX2icatYgjuDsMHgNsqtsXtuzB2iVpVzbZ71RBRsgw48ve8KdImUS4KDaGNEu0ILgVdmyAcvD1q7ZKKepo1P29CmJoPi9GIztFgKeHpRGGtdCy7NwRLkuiWrvMU4CZoHqGD8a4EgfgI1aNohFf+hebFFOovv8f4wvHbxkEcITLP8+bM6vfp8pI+u9VASQpAMVDtUFLeBBbw+MjOQdgYW3N9+GoUAUg9UTg7iL38qhbamPyTSHDdAVZINCSnQOv9dVrCiTgaeXKPxND2AGRdSBsTrsxSbTRFlfDjTFZLPR403DbTf8P1C+m4iP1zUOu97ffTmEePC+2DjEGlrUUJj+gQR+4cyAbo+qOkZMXtPzpGxycsKX628JxOsGdxZ5qT27T9gEUnO4/nXkrU+PWzkNWpZ6nQASessDtRhFMMMlBkA7/t7Gd0xLSc93XlqkjFgQO5lYQS8pMoP8ZR/dkHKeoejghaZx8/yWslZ/Z4UVgqndp0GLj4yZl8XQYyfBlD+jGVgFw6JH+t6JxU/hlNjTdN/dbvHFntTfltaZLO4evrznOw3xCD6Z+OauEj4gNZhmkHGDg0PVU8Mo4JIzD4XZZshqXylleMg=
  file:
    - "./dist/oracledb_exporter.linux-amd64"
    - "./dist/oracledb_exporter.darwin-amd64"
  on:
    repo: iamseth/oracledb_exporter
    tags: true

after_success:
  - cd ./dist
  - git init
  - git config --global user.name 'Jon'
  - git config --global user.email 'qianyanseu@gmail.com'
  - git add .
  - git commit -m "oracledb_exporter release, triggerd by travis ci"
  - git push --force "https://wangming1993:${REPO_TOKEN}@${GH_REF}" master:master

env:
  global:
    - GH_REF: github.com/qianyanseu/oracledb_exporter_release.git
